### PR TITLE
Add support for Fedora

### PR DESCRIPTION
**Pull request by jedigo**
Hi,
I have added basic support for installing Fedora.

### CODE REVIEW

**Comment by jedigo** [comment]
On my machine this installs Fedora 23 and 24 which work fine, but 25 beta fails to boot - I will investigate this further when 25 is out of beta. 

I have not added support yet for extra packages (chrome etc.) but I can do this if you think this is going to be worth merging,

Let me know if there are any issues.

**Comment by reynhout** [comment]
@jedigo Very nice, this is great!

I won't be able to look at it closely and test etc until early next week, but I look forward to doing so.

Which Chromebook/box model(s) have you been running Fedora on?

Thanks for the PR!

**Comment by jedigo** [comment]
I have  an Acer Chromebook 14 (edgar).

Sound doesn't work on this (or on Gallium), but everything else seems good.

**Comment by jedigo** [comment]
I have added all the customizations for Ubuntu into Fedora; however I am not sure that they are all working correctly  - I will take some time to validate all of these this week.

**Comment by reynhout** [comment]
@jedigo OK, thank you! I should be able to catch up and test this week as well.

**Comment by reynhout** [comment]
@jedigo I'm finally catching up with things here. :)

Thank you again, this all looks great -- it isn't quite working for me but I hope it's close.

I ran into two issues:

1. After running chrx with options `-d fedora`, (otherwise default), reboot hangs at "Booting from Hard Disk", which usually means that GRUB is not installed properly. I don't see that step take place in the logs, so that seems consistent.
2. There are a bunch of "no such file" errors when installing the `dist` customization files. The tar expansion is commented out in https://github.com/reynhout/chrx/pull/24/files#diff-0b67878d372f3798b6be78270f3c8d3dR923. Is this just part of your test env, or should the `dist` files not be installed the same way for Fedora?

Installing Fedora is nice and fast, and your method for using a Docker image opens up some possibilities for other distros too.

**Comment by reynhout** [comment]
I have the fully-merged repo installed on the secret chrx dev site. You can test with:

    export CHRX_WEB_ROOT=https://chrx.org/dev
    curl -O $CHRX_WEB_ROOT/go && sh go -v -d fedora

But I need to update it manually with new commits, of course.

**Comment by jedigo** [comment]
Hi,

Thanks for looking at this, I will be happy to keep on maintaining the fedora side of this code if you are happy to have another distro in your script.

I accidentally left in my test code -  just copying in the dist files from the git repo.

It's updated in the last commit, which also undoes some workarounds for a problem in f25 beta, which seem to have been updated in the source.

The actual full install of Fedora desktop does take a while longer than the minimal core install that kicks it off though, and the first boot also takes a few minutes.

This seems to be pretty good to me now; the only remaining issues are:
 - the sugar desktop spin seems to crash X as soon as it is started.
-  xbindkeys doesn't work in wayland (which is the default for gnome in f25)

I'll carry on investigating these, but the rest of it works on my machine.

I guess there are some other common post install things that be useful with fedora (enabling non-free codecs and the other software installs you already support on Ubuntu, like Kodi  etc.).

PS thanks for making the script in the first place, it made getting another OS onto my new chrome machine very easy, and when I wanted to change to using a different distro it was nice and simple to figure out how it worked.

**Comment by reynhout** [comment]
OK, I got a lot farther this time. And it took a bit longer as well. :)

Hitting a new problem now. Will need to investigate further, but let me know if anything jumps out at you:

Install completes, reboots properly, does the SELinux setup, reboots again and then hangs somewhere in the boot process after logging a few messages about the cht-bsw-max98090 driver not loading (audio chip, this is OK). Xorg does not start, switching to other VTs with Ctrl+Alt+Fx does not work. Same behaviour in both normal and rescue configs.

Checked the logfiles from ChromeOS. Found a few errors from `systemd` (inconsistent across boot attempts so far) and lots of "left unmapped" messages from SELinux (not sure if those are normal).

Maybe something specific to hardware? I'm testing on an Acer R11 CYAN, so we're both on Braswell, but there could be something else. My full arglist is `-v -d fedora`.

I don't know Fedora or SELinux well, though right now systemd looks like a prime suspect.

**Comment by jedigo** [comment]
this definitely sounds like an SELinux problem.

You can disable this by setting SELINUX=disabled in the /etc/selinux/config file.

I'd be interested to know if this isa one off or if it occurs regularly on the chrome hardware for some reason. This failure to label properly is new to me certainly, and if its common, it may be best to disable it and let people who need it enable it themselves.

**Comment by reynhout** [comment]
OK, I will try that.

I left the machine in "boot hang" overnight, with `quiet` removed from kernel params so I could see the messages on the display. There was another burst of SELinux messages at 9527 seconds (again `Context ... is not valid (left unmapped)`), but nothing else informative.

**Comment by reynhout** [comment]
@jedigo Disabling SELinux fixed it. Boot succeeded, and from a quick test things look good. No audio of course.

**Comment by reynhout** [comment]
@jedigo It looks like Fedora configures SELinux by default, right? I don't see any explicit setup in your config files. Is there a preferable way to disable it, or should we include a `/etc/selinux/config` file to do so?

**Comment by jedigo** [comment]
Hi,
 I have been a bit slow as I have had a winter flu and been recovering for a while.

I updated this to disable all selinux, but didn't update the pr.

Anyway, it should be good to go now.

**Comment by reynhout** [comment]
@jedigo Great, thank you. I'll be able to test it today, or this weekend at the latest.

When we merge your Fedora code into the release, we should post an announcement on /r/ChrUbuntu, and maybe /r/ChromeOS? Can you think of anywhere else to notify?

We should probably leave it marked "beta" or experimental for a couple weeks until we get some feedback from testing on other models. I can test on PEPPY (Haswell) and CYAN (Braswell). Broadwell should follow Haswell pretty closely, but Skylake is unknown, and Bay Trail is always a wild card.

**Comment by jedigo** [comment]
I'd agree, definitely experimental at this stage.

I'm not sure how many (if any) would prefer Fedora to Ubuntu or Gallium, so it may be some time before you get reports.

As for announcements, maybe /r/Fedora as well?

**Comment by reynhout** [comment]
Hopefully we'll get some broad testing. Users on /r/ChrUbuntu are pretty experimental with their Chromebooks.

Posting to /r/Fedora is a good idea too. Should get some exposure there to people who wouldn't otherwise know that Linux-on-Chromebook is an option.

I'll write an announcement up for /r/ChrUbuntu today. Are you /u/jedigo on Reddit as well?

I've merged all of your changes in locally (and published to dev site), and everything looks good. Before pushing to github and prod, I'll update the README and disable Fedora 25 selection in the code (currently allows selection of other versions, but always downloads F24, right?)

For the README, I measured Fedora 24 installed disk space is 4.5GB, and RAM at idle is 647MB. My total install time is 27min. Do those numbers seem right to you?

**Comment by jedigo** [comment]
Hi, the numbers seem OK, a little slow, but I haven't been testing too much
with gnome, as it is pretty big, and also not really my desktop of choice.

Also, that is me on reddit, although I don't post much.

You can select 25, and that will get installed. We just use a constant
docker image, which is tiny, but the actual installation uses --releasever
to install the correct version from the repo mirror.

This all works fine, and F25 seems pretty stable now, and should be
released next week I think. I've tested installing small versions of 22,
23, 24 and 25 without any issues, apart from mousepad drivers in old
versions.

Try using -r 25 -e lxde for a smaller install to test this out, if minimal
is too minimal.

**Comment by reynhout** [comment]
OK, I wondered if I was missing something there. Where/how does the system get installed with a different version (CHRX_OS_RELEASE?) after the Docker image bootstrap?

**Comment by jedigo** [comment]
Yep, check line 860 - it makes an installation chroot from the docker image, and then installs the actual system there - again a fairly minimal install ( just the core group) before moving on to the post install steps.
  
    chroot ${CHRX_INSTALL_ROOT}/fedora /bin/bash -c "dnf -y --nogpgcheck --releasever=${CHRX_OS_VERSION} --installroot=/mnt/ group install core"

**Comment by reynhout** [comment]
Ah, there it is. I was grepping for the wrong variable.

I'm testing one more time with a bunch of command line options, and updating the README. All looks good so far. It looks like the `-p` option will only work on the Debian-derivatives, but the others should be good I think.

**Comment by jedigo** [comment]
Yep that was for a later day - I'd think the first use of that would be to pick up nonfree codecs, but I haven't yet got round to it.

**Comment by reynhout** [comment]
OK, code is merged, README updated, and all and pushed to GitHub and chrx.org. I tested an install with LXDE as well to get some more balanced numbers.

/r/ChrUbuntu announcement here: https://www.reddit.com/r/chrubuntu/comments/5e6gtg/fedora_support_has_been_added_to_chrx/

**Comment by idvoretskyi** [comment]
@jedigo @reynhout any documentation is available?

**Comment by reynhout** [comment]
@idvoretskyi The docs on chrx.org have been updated with Fedora details. Is that what you're looking for?

**Comment by idvoretskyi** [comment]
@reynhout looks good, thank you.

**Comment by mrjohnc** [comment]
> Hi,
> I have added basic support for installing Fedora.

Hi @jedigo could you pretty pretty please add support for Manjaro? I'm not a developer but I would be very happy to do any legwork needed, find info etc.

**Pull request merged**
